name: geek_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
 # flutter 3.19.0
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flextras: ^1.0.0
  flutter_animate: ^4.3.0
  flutter_modular: ^6.3.2
  internet_connection_checker_plus: ^2.2.0
  intl: ^0.18.1
  path_provider: ^2.1.2
  path_provider_foundation: ^2.3.2
  flutter_vibrate: ^1.3.0
  toastification: ^1.2.1
  supabase: ^2.0.7
  gap: ^3.0.1
  loading_animation_widget: ^1.2.0+4
  fast_cached_network_image: ^1.2.7
  custom_refresh_indicator: ^3.0.0
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"
   
flutter_launcher_icons:
  #ANDROID
  android: "launcher_icon"
  image_path: "assets/logo/ANDROID.png"
  adaptive_icon_foreground: "assets/logo/ANDROID.png"
  adaptive_icon_background: "#131323"
  #IOS
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/logo/IOS.png"
  #WEB
  web:
    generate: true
    image_path: "assets/logo/WINDOWS.png"
    background_color: "#131323"
    theme_color: "#131323"
  #WINDOWS
  windows:
    generate: true
    image_path: "assets/logo/WINDOWS.png"
    icon_size: 48 # min:48, max:256, default: 48
  #MACOS
  macos:
    generate: true
    image_path: "assets/logo/MACOS.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
  
 